name: ElysiumItems
version: ${project.version}
main: com.github.lukethadley.elysiumitems.ElysiumItems
api-version: 1.19
authors: [ Thomas9078 ]
commands:
  elysiumtools:
    description: a test command
    usage: /elysiumtools [give | list] {toolname} {playername}
    permission: elysiumitems.givetools
  elysiumarmor:
    description: a test command
    usage: /elysiumarmor [give | list] {toolname} {playername}
    permission: elysiumitems.givearmor
permissions:
  elysiumitems.givearmor:
    default: op
  elysiumitems.givetools:
    default: op